### ISSUE TITLE
Comment doesn't change with go file

### ISSUE THREAD

**Issue by alitdarmaputra** [KarimElghamry/vim-auto-comment#1]
Hello, I use nvim and want to use your plugin. But when I tried to add go extension in inline dictionary seem it doesn't work well and the comment for .go use "#"

```
let g:inline_comment_dict = {
		\'//': ["js", "ts", "cpp", "c", "dart", "go"],
		\'#': ['py', 'sh'],
		\'"': ['vim'],
		\}
```
Thank you

**Comment by KarimElghamry** [comment]
Hello @alitdarmaputra! thank you for checking out this plugin and pointing out this issue. I've fixed this issue in the latest commit 475b08af34128fd6aac64790ab8b891b98bf15ac on the `master` branch. Please update your plugin.

If you have any other issues, I'd be glad to help. I'll close this issue now, feel free to reopen it at anytime.
